# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a295d36b851517d58b775912051792a41f84c3d340e8122340469cbf1e833d47414e84d83b123e8e40ab99f0b4e9f52a905dd6c6446ff0854c399121a856262

test:
  secret_key_base: 00247e91de581a9242e14c85d0a70fd96641e0a490dea7da398a0f38fb402203e78b92d2b219ae069eadbc53faea926d2ae7a1d4fd7f6d9bf664492b4fe73fb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
